CATEGORY_PACKAGE = "JN Suite"

CATEGORY_IMAGE = f"{CATEGORY_PACKAGE}/Image"
CATEGORY_OTHER = f"{CATEGORY_PACKAGE}/Other"
CATEGORY_PATCH = f"{CATEGORY_PACKAGE}/Patch"
CATEGORY_PRIMITIVE = f"{CATEGORY_PACKAGE}/Primitive"
CATEGORY_PRIMITIVE_CONVERSION = f"{CATEGORY_PACKAGE}/Primitive/Conversion"
CATEGORY_PRIMITIVE_PROCESS = f"{CATEGORY_PACKAGE}/Primitive/Process"
CATEGORY_SAMPLING = f"{CATEGORY_PACKAGE}/Sampling"
CATEGORY_WORKFLOW = f"{CATEGORY_PACKAGE}/Workflow"

DIRECTIONS = ["none", "both", "horizontal", "vertical"]
